Added support for displaying an information page when the internet gateway becomes unreachable (= no default route) as per ticket #13.

diff --git a/package/nodewatcher/files/check_dns b/package/nodewatcher/files/check_dns
--- a/package/nodewatcher/files/check_dns
+++ b/package/nodewatcher/files/check_dns
@@ -14,17 +14,22 @@ else
   /etc/init.d/dnsmasq start
 fi
 
-# Remote checks (are DNS resolutions actually working?)
-DNS_RESPONSE="`nslookup ${LOOKUP_REMOTE}`"
-if [ "$?" == "0" ]; then
-  # Verify if record matches
-  if [ "`echo ${DNS_RESPONSE} | awk '{ print $11 }'`" != "${REMOTE_RESPONSE}" ]; then
-    echo -n "2" > /var/dns_test_remote
+if [ ! -f /tmp/traffic_redirection_enabled ]; then
+  # Remote checks (are DNS resolutions actually working?)
+  DNS_RESPONSE="`nslookup ${LOOKUP_REMOTE}`"
+  if [ "$?" == "0" ]; then
+    # Verify if record matches
+    if [ "`echo ${DNS_RESPONSE} | awk '{ print $11 }'`" != "${REMOTE_RESPONSE}" ]; then
+      echo -n "2" > /var/dns_test_remote
+    else
+      echo -n "0" > /var/dns_test_remote
+    fi
   else
-    echo -n "0" > /var/dns_test_remote
+    # Failed to resolve remote record
+    echo -n "1" > /var/dns_test_remote
   fi
 else
-  # Failed to resolve remote record
+  # Since traffic redirection is enabled, report remote DNS as ok
   echo -n "1" > /var/dns_test_remote
 fi
 
