Retry remote DNS check 5 times with 1 second delay inbetween. Also fixed a problem where DNS status was always reported as failed instead of ok when redirection was enabled.

diff --git a/package/nodewatcher/files/check_dns b/package/nodewatcher/files/check_dns
--- a/package/nodewatcher/files/check_dns
+++ b/package/nodewatcher/files/check_dns
@@ -16,21 +16,30 @@ if [ ! -f /tmp/traffic_redirection_enabled ]; then
   fi
 
   # Remote checks (are DNS resolutions actually working?)
-  DNS_RESPONSE="`nslookup ${LOOKUP_REMOTE}`"
-  if [ "$?" == "0" ]; then
-    # Verify if record matches
-    if [ "`echo ${DNS_RESPONSE} | awk '{ print $11 }'`" != "${REMOTE_RESPONSE}" ]; then
-      echo -n "2" > /var/dns_test_remote
+  DNS_RESULT="1"
+  for _ in $(seq 1 5); do
+    DNS_RESPONSE="`nslookup ${LOOKUP_REMOTE}`"
+    if [ "$?" == "0" ]; then
+      # Verify if record matches
+      if [ "`echo ${DNS_RESPONSE} | awk '{ print $11 }'`" != "${REMOTE_RESPONSE}" ]; then
+        DNS_RESULT="2"
+      else
+        DNS_RESULT="0"
+      fi
+
+      break
     else
-      echo -n "0" > /var/dns_test_remote
+      # Failed to resolve remote record, retry again in one second
+      DNS_RESULT="1"
+      sleep 1
     fi
-  else
-    # Failed to resolve remote record
-    echo -n "1" > /var/dns_test_remote
-  fi
+  done
+  
+  # Save remote test result
+  echo -n "${DNS_RESULT}" > /var/dns_test_remote
 else
   # Since traffic redirection is enabled, report DNS as ok
-  echo -n "1" > /var/dns_test_local
-  echo -n "1" > /var/dns_test_remote
+  echo -n "0" > /var/dns_test_local
+  echo -n "0" > /var/dns_test_remote
 fi
 
